In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
pip install setuptools

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
##Define the vocabulary size
voc_size=10000

In [8]:
#One Hot Reresentation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr
    

[[7305, 2359, 6006, 6526],
 [7305, 2359, 6006, 7271],
 [7305, 4468, 6006, 3371],
 [1210, 3867, 2864, 3885, 8715],
 [1210, 3867, 2864, 3885, 2555],
 [3568, 7305, 7284, 6006, 55],
 [6608, 236, 1619, 3885]]

In [9]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_length=8
embedded_doc=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 7305 2359 6006 6526]
 [   0    0    0    0 7305 2359 6006 7271]
 [   0    0    0    0 7305 4468 6006 3371]
 [   0    0    0 1210 3867 2864 3885 8715]
 [   0    0    0 1210 3867 2864 3885 2555]
 [   0    0    0 3568 7305 7284 6006   55]
 [   0    0    0    0 6608  236 1619 3885]]


In [12]:
#feature representation
dim=10


In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\yelle\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[[ 1.98383071e-02, -3.44486013e-02, -1.93199515e-02,
          4.49441932e-02,  1.63249113e-02, -4.17498127e-02,
          4.88865636e-02, -1.80540793e-02,  4.80367430e-02,
          1.36693157e-02],
        [ 1.98383071e-02, -3.44486013e-02, -1.93199515e-02,
          4.49441932e-02,  1.63249113e-02, -4.17498127e-02,
          4.88865636e-02, -1.80540793e-02,  4.80367430e-02,
          1.36693157e-02],
        [ 1.98383071e-02, -3.44486013e-02, -1.93199515e-02,
          4.49441932e-02,  1.63249113e-02, -4.17498127e-02,
          4.88865636e-02, -1.80540793e-02,  4.80367430e-02,
          1.36693157e-02],
        [ 1.98383071e-02, -3.44486013e-02, -1.93199515e-02,
          4.49441932e-02,  1.63249113e-02, -4.17498127e-02,
          4.88865636e-02, -1.80540793e-02,  4.80367430e-02,
          1.36693157e-02],
        [ 3.67324837e-02,  1.63015239e-02,  2.18437202e-02,
          2.50272490e-02, -1.73606053e-02, -7.53545761e-03,
          4.18130495e-02, -3.53872664e-02,  2.219896

In [17]:
embedded_doc[0]

array([   0,    0,    0,    0, 7305, 2359, 6006, 6526])

In [19]:
import numpy as np
model.predict(np.expand_dims(embedded_doc[0], axis=0))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step


array([[[ 0.01983831, -0.0344486 , -0.01931995,  0.04494419,
          0.01632491, -0.04174981,  0.04888656, -0.01805408,
          0.04803674,  0.01366932],
        [ 0.01983831, -0.0344486 , -0.01931995,  0.04494419,
          0.01632491, -0.04174981,  0.04888656, -0.01805408,
          0.04803674,  0.01366932],
        [ 0.01983831, -0.0344486 , -0.01931995,  0.04494419,
          0.01632491, -0.04174981,  0.04888656, -0.01805408,
          0.04803674,  0.01366932],
        [ 0.01983831, -0.0344486 , -0.01931995,  0.04494419,
          0.01632491, -0.04174981,  0.04888656, -0.01805408,
          0.04803674,  0.01366932],
        [ 0.03673248,  0.01630152,  0.02184372,  0.02502725,
         -0.01736061, -0.00753546,  0.04181305, -0.03538727,
          0.02219896, -0.0313686 ],
        [-0.0470346 ,  0.02500793,  0.03942379,  0.0402424 ,
          0.04409358, -0.00944667,  0.00034981, -0.03452698,
         -0.01935821, -0.04353892],
        [-0.00847161, -0.0003625 ,  0.00475055,  0.0